In [ ]:
print("abc")

abc

In [1]:
! pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/7b/8b/721a9cff6fa6a91b162eb51019c6243b82b3226c71bb6c8ef4a9bd65cbc6/pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Obtaining dependency information for numpy>=1.26.0 from https://files.pythonhosted.org/packages/2d/5b/e1deebf88ff431b01b7406ca3583ab2bbb90972bbe1c568732e49c844f7e/numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kushm.desktop-rm39q8o.000\desktop\python-learn-kmc\pandas\env\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Obtaining dependency information for tzdata from https://files.pythonhosted.org/packages/ce/e4/dccd7f47c4b64213ac01ef921a1337ee6e30e8c6466046018326977efd95/tzdata-2026.2-py2.py3-none-any.whl.metadata
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\kushm.desktop-rm39q8o.000\desktop\python-learn-kmc\pandas\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB 325.1 kB/s eta 0:00:30
   ---------------------------------------- 0.0/9.7 MB 281.8 kB/s eta 0:00:35
   ---------------------------------------- 0.1/9.7 MB 328.2 kB/s eta 0:00:30
   ---------------------------------------- 0.1/9.7 MB 403.5 kB/s eta 0:00:24
   ---------------------------------------- 0.1/9.7 MB 403.5 kB/s eta 0:00:24
    --------------------------------------- 0.1/9.7 MB 425.3 kB/s eta 0:00:23
    --------------------------------------- 0.2/9.7 MB 506.0 kB/s eta 0:00:19
    --------------------------------------- 0.2/9.7 MB 573.4 kB/s eta 0:00:17
   - -------------------------------------- 0.3/9.7 MB 610.3 kB/s eta 0:00:16
   - -------------------------------------- 0.4/9.7 MB 819.2 kB/s eta 0:00:12
   - -------------------------------------- 0.5/9.7 MB 861.1 kB/s eta 0:00:11
   - -------------------------------------- 0.5/9.7 MB 861.1 kB/s eta 0:00:11
   - -------------------------------------- 0.5/9.7 MB 861.1 kB/s eta 0:00:11
   -- ------------------------------------- 0.6/9.7 MB 833.5 kB/s eta 0:00:11
   -- ------------------------------------- 0.7/9.7 MB 934.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.7 MB 983.4 kB/s eta 0:00:10
   --- ------------------------------------ 0.9/9.7 MB 1.1 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/9.7 MB 1.1 MB/s eta 0:00:09
   ---- ----------------------------------- 1.1/9.7 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.2/9.7 MB 1.2 MB/s eta 0:00:08
   ----- ---------------------------------- 1.3/9.7 MB 1.2 MB/s eta 0:00:07
   ----- ---------------------------------- 1.4/9.7 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.5/9.7 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.6/9.7 MB 1.4 MB/s eta 0:00:07
   ------- -------------------------------- 1.7/9.7 MB 1.4 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.7 MB 1.4 MB/s eta 0:00:06
   ------- -------------------------------- 1.9/9.7 MB 1.4 MB/s eta 0:00:06
   -------- ------------------------------- 2.0/9.7 MB 1.4 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.7 MB 1.5 MB/s eta 0:00:06
   --------- ------------------------------ 2.2/9.7 MB 1.5 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.7 MB 1.5 MB/s eta 0:00:05
   ---------- ----------------------------- 2.5/9.7 MB 1.6 MB/s eta 0:00:05
   ---------- ----------------------------- 2.6/9.7 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.7/9.7 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.7 MB 1.7 MB/s eta 0:00:05
   ------------ --------------------------- 3.0/9.7 MB 1.7 MB/s eta 0:00:04
   ------------- -------------------------- 3.2/9.7 MB 1.7 MB/s eta 0:00:04
   ------------- -------------------------- 3.3/9.7 MB 1.8 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.7 MB 1.8 MB/s eta 0:00:04
   -------------- ------------------------- 3.4/9.7 MB 1.8 MB/s eta 0:00:04
   -------------- ------------------------- 3.6/9.7 MB 1.8 MB/s eta 0:00:04
   --------------- ------------------------ 3.8/9.7 MB 1.8 MB/s eta 0:00:04
   --------------- ------------------------ 3.9/9.7 MB 1.8 MB/s eta 0:00:04
   ---------------- ----------------------- 4.0/9.7 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.7 MB 1.9 MB/s eta 0:00:03
   ----------------- ---------------------- 4.3/9.7 MB 1.9 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.7 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.7 MB 2.0 MB/s eta 0:00:03
   ------------------- -------------------- 4.8/9.7 MB 2.0 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.7 MB 2.0 MB/s eta 0:00:03
   --------------------- ------------------ 5.1/9.7 MB 2.0 MB/s eta 0:00:03
   --------------------- ------------------ 5.3/9.7 MB 2.1 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.7 MB 2.1 MB/s eta 0:00:03
   ----------------------- ---------------- 5.7/9.7 MB 2.1 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.7 MB 2.1 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.7 MB 2.2 MB/s eta 0:00:02
   ------------------------- -------------- 6.2/9.7 MB 2.2 MB/s eta 0:00:02
   -------------------------- ------------- 6.3/9.7 MB 2.2 MB/s eta 0:00:02
   -------------------------- ------------- 6.5/9.7 MB 2.2 MB/s eta 0:00:02
   --------------------------- ------------ 6.7/9.7 MB 2.3 MB/s eta 0:00:02
   ---------------------------- ----------- 6.9/9.7 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.7 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 7.2/9.7 MB 2.3 MB/s eta 0:00:02
   ------------------------------ --------- 7.5/9.7 MB 2.4 MB/s eta 0:00:01
   ------------------------------- -------- 7.7/9.7 MB 2.4 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 2.4 MB/s eta 0:00:01
   --------------------------------- ------ 8.2/9.7 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.7 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.6/9.7 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.8/9.7 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.1/9.7 MB 2.6 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 9.5/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  9.6/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 2.6 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/12.3 MB 10.6 MB/s eta 0:00:02
   - -------------------------------------- 0.6/12.3 MB 7.1 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/12.3 MB 5.1 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/12.3 MB 4.4 MB/s eta 0:00:03
   --- ------------------------------------ 1.1/12.3 MB 4.6 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.3 MB 4.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.3 MB 4.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.7/12.3 MB 4.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.7/12.3 MB 4.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.3 MB 3.6 MB/s eta 0:00:03
   ------ --------------------------------- 2.0/12.3 MB 3.8 MB/s eta 0:00:03
   ------- -------------------------------- 2.2/12.3 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.5/12.3 MB 4.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.7/12.3 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.3 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.3 MB 3.9 MB/s eta 0:00:03
   ---------- ----------------------------- 3.3/12.3 MB 3.9 MB/s eta 0:00:03
   ----------- ---------------------------- 3.6/12.3 MB 4.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.8/12.3 MB 4.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.3 MB 4.0 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.3 MB 4.0 MB/s eta 0:00:03
   -------------- ------------------------- 4.4/12.3 MB 4.1 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.3 MB 4.0 MB/s eta 0:00:02
   --------------- ------------------------ 4.8/12.3 MB 4.0 MB/s eta 0:00:02
   ---------------- ----------------------- 5.0/12.3 MB 4.0 MB/s eta 0:00:02
   ----------------- ---------------------- 5.3/12.3 MB 4.1 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.3 MB 4.1 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.3 MB 4.1 MB/s eta 0:00:02
   ------------------ --------------------- 5.6/12.3 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 5.7/12.3 MB 3.8 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.3 MB 3.8 MB/s eta 0:00:02
   ------------------- -------------------- 6.1/12.3 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 6.2/12.3 MB 3.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.4/12.3 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.3 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 6.8/12.3 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 7.0/12.3 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 7.2/12.3 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 7.4/12.3 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 7.4/12.3 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 7.5/12.3 MB 3.7 MB/s eta 0:00:02
   ------------------------- -------------- 7.8/12.3 MB 3.7 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.3 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 8.3/12.3 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 8.6/12.3 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 8.8/12.3 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.0/12.3 MB 3.8 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 3.8 MB/s eta 0:00:01
   ------------------------------ --------- 9.3/12.3 MB 3.8 MB/s eta 0:00:01
   ------------------------------ --------- 9.5/12.3 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 3.8 MB/s eta 0:00:01
   -------------------------------- ------- 9.9/12.3 MB 3.8 MB/s eta 0:00:01
   -------------------------------- ------- 10.1/12.3 MB 3.9 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.3 MB 3.8 MB/s eta 0:00:01
   ---------------------------------- ----- 10.6/12.3 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 3.8 MB/s eta 0:00:01
   ----------------------------------- ---- 11.1/12.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.4/12.3 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.6/12.3 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 3.8 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
   ---------------------------------------- 0.0/349.3 kB ? eta -:--:--
   --------------------------------------  348.2/349.3 kB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 349.3/349.3 kB 5.4 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.2

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [6]:
# creating series from the list
data = [1,2,3,4,5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
# custom index
marks= pd.Series([90, 80, 70], index = ['Maths', 'Science', 'English'])
marks

Maths      90
Science    80
English    70
dtype: int64

In [12]:
marks['Maths']

np.int64(90)

In [14]:
print(marks['Maths'])

90

In [16]:
# creating series from dictionary
data_dict = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data_dict)
series_dict

a    1
b    2
c    3
dtype: int64

In [ ]:
# creating scalar data -> when we want to assign a single value ot all
series = pd.Series(5, index=["Ram", "Shyam", "Hari"])
series

Ram      5
Shyam    5
Hari     5
dtype: int64

In [18]:
print(series)

Ram      5
Shyam    5
Hari     5
dtype: int64

In [21]:
# Accessing Series Data
marks = pd.Series([80,90,70,60], index=['a', 'b','c', 'd'])
marks # last ma variable lai rakhyo vane print garna pardaina

a    80
b    90
c    70
d    60
dtype: int64

In [ ]:
print(marks.iloc[0]) # iloc -> integer location

80

In [24]:
print(marks.iloc[4])

IndexError: single positional indexer is out-of-bounds

In [25]:
print(marks.iloc[3])

60

In [27]:
# accessed by label
print(marks["a"])
print(marks['b'])

80
90

In [29]:
marks['a']

np.int64(80)

In [31]:
# Series real example
stock_prices = pd.Series([157, 156, 143, 123, 453], index = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'])

In [33]:
print(stock_prices['Tuesday'])

156

In [35]:
print(stock_prices.mean())

206.4

In [38]:
print(stock_prices.max())

453

In [39]:
print(stock_prices.min())

123

In [41]:
print(stock_prices[stock_prices>150])

Monday     157
Tuesday    156
Friday     453
dtype: int64

In [42]:
print(stock_prices>150)

Monday        True
Tuesday       True
Wednesday    False
Thursday     False
Friday        True
dtype: bool

Data Frame with two-dimensional data with rows and column

In [45]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Kathmandu', 'Bhaktapur', 'Lalitpur']
}

In [46]:
df = pd.DataFrame(data)
pd(df)

TypeError: 'module' object is not callable

In [48]:
print(df)

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [49]:
print(df.head())

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [50]:
print(df.head(1))

    Name  Age       City
0  Alice   25  Kathmandu

In [52]:
print(df.tail())

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [54]:
print(df.tail(1))

      Name  Age      City
2  Charlie   35  Lalitpur

In [55]:
print(df.shape())

TypeError: 'tuple' object is not callable

In [57]:
print(df.shape) # no. of rows and columns print garxa

(3, 3)

In [58]:
# column name 
print(df.columns)

Index(['Name', 'Age', 'City'], dtype='str')

In [59]:
print(df.rpow)

<bound method DataFrame.rpow of       Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur>

In [75]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [77]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [78]:
df.des

AttributeError: 'DataFrame' object has no attribute 'des'

In [71]:
df.describe

<bound method NDFrame.describe of       Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur>

In [73]:
df.info

<bound method DataFrame.info of       Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur>

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [81]:
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [83]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [85]:
df.Age

0    25
1    30
2    35
Name: Age, dtype: int64

In [88]:
df.City

0    Kathmandu
1    Bhaktapur
2     Lalitpur
Name: City, dtype: str

In [89]:
df['Name','Age']

KeyError: ('Name', 'Age')

In [91]:
df.[['Name', 'Age', 'City']]

SyntaxError: invalid syntax (2525195498.py, line 1)

In [93]:
df[['Name', 'Age', 'City']]

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [94]:
# access by position row-wise
df.iloc[0]

Name        Alice
Age            25
City    Kathmandu
Name: 0, dtype: object

In [97]:
# Filtering dataframe
filtered_df = df[df['Age']>28]
print(filtered_df)

      Name  Age       City
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [98]:
# Multiple Condtions 
# And Consitions

filtered_df = df[(df['Age']>28) & (df['City'] =='Bhaktapur')]
print(filtered_df)

  Name  Age       City
1  Bob   30  Bhaktapur

In [100]:
# OR Consitions

filtered_df = df[(df['Age']>28) | (df['City'] =='Bhaktapur')]
print(filtered_df)

      Name  Age       City
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [103]:
# And Consitions

filtered_df = df[ not ((df['Age']>28) & (df['City'] =='Bhaktapur'))]
print(filtered_df)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [106]:
filtered_df = df[ not (df['Age']>28)]
print(filtered_df)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [107]:
filtered_df = df[ ((df['Age']>28) , (df['City'] =='Bhaktapur'))]
print(filtered_df)

InvalidIndexError: (0    False
1     True
2     True
Name: Age, dtype: bool, 0    False
1     True
2    False
Name: City, dtype: bool)

In [108]:
filtered_df = df[ (df['Age']>28)  (df['City'] =='Bhaktapur')]
print(filtered_df)

TypeError: 'Series' object is not callable

CRUD -> ADD, Update, Delete (to the existing table)

In [141]:
# ADD a new column
df['Salary'] = [50000, 60000, 70000]
print(df)

      Name  Age       City  Salary
0    Alice   25  Kathmandu   50000
1      Bob   30  Bhaktapur   60000
2  Charlie   35   Lalitpur   70000

In [142]:
# Update existing column
df['Salary'] = df['Salary'] + 5000
print(df)

      Name  Age       City  Salary
0    Alice   25  Kathmandu   55000
1      Bob   30  Bhaktapur   65000
2  Charlie   35   Lalitpur   75000

In [ ]:
# Update existing column with condition
df.loc[df['Age']>30, 'Salary'] = df['Salary'] + 10000
print(df)

      Name  Age       City  Salary
0    Alice   25  Kathmandu   55000
1      Bob   30  Bhaktapur   65000
2  Charlie   35   Lalitpur   85000

In [144]:
# Deleting a column
df.drop('Salary', axis=1, inplace=True)
print(df)

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30  Bhaktapur
2  Charlie   35   Lalitpur

In [145]:
df.drop('Salary')
print(df)

KeyError: "['Salary'] not found in axis"

In [147]:
df.drop('Salary', axis=0, inplace=True)
print(df)

KeyError: "['Salary'] not found in axis"

In [149]:
df.drop(0, axis=1, inplace=True)
print(df)

KeyError: '[0] not found in axis'

In [151]:
# Delete row
df.drop(0, axis=0, inplace=True)
print(df)

KeyError: '[0] not found in axis'

In [152]:
# Read CSV file
df = pd.read_csv('test1.csv')

In [156]:
print(df)

    first_name  last_name                   company_name  \
0        James       Butt              Benton, John B Jr
1    Josephine    Darakjy          Chanay, Jeffrey A Esq
2          Art     Venere            Chemel, James L Cpa
3        Lenna   Paprocki         Feltz Printing Service
4      Donette     Foller            Printing Dimensions
..         ...        ...                            ...
495    Brittni  Gillaspie                    Inner Label
496    Raylene      Kampa                     Hermar Inc
497        Flo   Bookamer   Simonton Howe & Schneider Pc
498       Jani      Biddy  Warehouse Office & Paper Prod
499   Chauncey     Motley     Affiliated With Travelodge

                  address        city      county state    zip        phone1  \
0      6649 N Blue Gum St         NaN     Orleans    LA  70116  504-621-8927
1     4 B Blue Ridge Blvd    Brighton  Livingston    MI  48116  810-292-9388
2    8 W Cerritos Ave #54  Bridgeport  Gloucester    NJ   8014  856-636-8749
3             639 Main St   Anchorage   Anchorage    AK  99501  907-385-4412
4            34 Center St    Hamilton      Butler    OH  45011  513-570-1893
..                    ...         ...         ...   ...    ...           ...
495            67 Rv Cent       Boise         Ada    ID  83709  208-709-1235
496        2 Sw Nyberg Rd     Elkhart     Elkhart    IN  46514  574-499-1454
497       89992 E 15th St    Alliance   Box Butte    NE  69301  308-726-2182
498      61556 W 20th Ave     Seattle        King    WA  98104  206-711-6498
499        63 E Aurora Dr     Orlando      Orange    FL  32804  407-413-4842

           phone2                          email  \
0    504-845-1427                jbutt@gmail.com
1    810-374-9840  josephine_darakjy@darakjy.org
2    856-264-4130                 art@venere.org
3    907-921-2010          lpaprocki@hotmail.com
4    513-549-4561         donette.foller@cox.net
..            ...                            ...
495  208-206-9848       bgillaspie@gillaspie.com
496  574-330-1884               rkampa@kampa.org
497  308-250-6987           flo.bookamer@cox.net
498  206-395-6284               jbiddy@yahoo.com
499  407-557-8857        chauncey_motley@aol.com

                                         web
0               http://www.bentonjohnbjr.com
1           http://www.chanayjeffreyaesq.com
2             http://www.chemeljameslcpa.com
3        http://www.feltzprintingservice.com
4          http://www.printingdimensions.com
..                                       ...
495                http://www.innerlabel.com
496                 http://www.hermarinc.com
497   http://www.simontonhoweschneiderpc.com
498  http://www.warehouseofficepaperprod.com
499  http://www.affiliatedwithtravelodge.com

[500 rows x 12 columns]

In [159]:
df

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,NaN,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,http://www.innerlabel.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,574-499-1454,574-330-1884,rkampa@kampa.org,http://www.hermarinc.com
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,308-726-2182,308-250-6987,flo.bookamer@cox.net,http://www.simontonhoweschneiderpc.com
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,206-711-6498,206-395-6284,jbiddy@yahoo.com,http://www.warehouseofficepaperprod.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,407-413-4842,407-557-8857,chauncey_motley@aol.com,http://www.affiliatedwithtravelodge.com

In [ ]:
df.head() # by default first 5 print garxa

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,NaN,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com

In [ ]:
df.tail() # # by default last 5 print garxa

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,http://www.innerlabel.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,574-499-1454,574-330-1884,rkampa@kampa.org,http://www.hermarinc.com
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,308-726-2182,308-250-6987,flo.bookamer@cox.net,http://www.simontonhoweschneiderpc.com
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,206-711-6498,206-395-6284,jbiddy@yahoo.com,http://www.warehouseofficepaperprod.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,407-413-4842,407-557-8857,chauncey_motley@aol.com,http://www.affiliatedwithtravelodge.com

In [165]:
df.columns

Index(['first_name', 'last_name', 'company_name', 'address', 'city', 'county',
       'state', 'zip', 'phone1', 'phone2', 'email', 'web'],
      dtype='str')

In [167]:
df.head(1)

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,NaN,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com

In [169]:
df.isnull()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False

In [171]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    500 non-null    str
 1   last_name     500 non-null    str
 2   company_name  500 non-null    str
 3   address       500 non-null    str
 4   city          499 non-null    str
 5   county        500 non-null    str
 6   state         500 non-null    str
 7   zip           500 non-null    int64
 8   phone1        500 non-null    str
 9   phone2        500 non-null    str
 10  email         500 non-null    str
 11  web           500 non-null    str
dtypes: int64(1), str(11)
memory usage: 47.0 KB

In [173]:
df.shape

(500, 12)

In [174]:
print(df)

    first_name  last_name                   company_name  \
0        James       Butt              Benton, John B Jr
1    Josephine    Darakjy          Chanay, Jeffrey A Esq
2          Art     Venere            Chemel, James L Cpa
3        Lenna   Paprocki         Feltz Printing Service
4      Donette     Foller            Printing Dimensions
..         ...        ...                            ...
495    Brittni  Gillaspie                    Inner Label
496    Raylene      Kampa                     Hermar Inc
497        Flo   Bookamer   Simonton Howe & Schneider Pc
498       Jani      Biddy  Warehouse Office & Paper Prod
499   Chauncey     Motley     Affiliated With Travelodge

                  address        city      county state    zip        phone1  \
0      6649 N Blue Gum St         NaN     Orleans    LA  70116  504-621-8927
1     4 B Blue Ridge Blvd    Brighton  Livingston    MI  48116  810-292-9388
2    8 W Cerritos Ave #54  Bridgeport  Gloucester    NJ   8014  856-636-8749
3             639 Main St   Anchorage   Anchorage    AK  99501  907-385-4412
4            34 Center St    Hamilton      Butler    OH  45011  513-570-1893
..                    ...         ...         ...   ...    ...           ...
495            67 Rv Cent       Boise         Ada    ID  83709  208-709-1235
496        2 Sw Nyberg Rd     Elkhart     Elkhart    IN  46514  574-499-1454
497       89992 E 15th St    Alliance   Box Butte    NE  69301  308-726-2182
498      61556 W 20th Ave     Seattle        King    WA  98104  206-711-6498
499        63 E Aurora Dr     Orlando      Orange    FL  32804  407-413-4842

           phone2                          email  \
0    504-845-1427                jbutt@gmail.com
1    810-374-9840  josephine_darakjy@darakjy.org
2    856-264-4130                 art@venere.org
3    907-921-2010          lpaprocki@hotmail.com
4    513-549-4561         donette.foller@cox.net
..            ...                            ...
495  208-206-9848       bgillaspie@gillaspie.com
496  574-330-1884               rkampa@kampa.org
497  308-250-6987           flo.bookamer@cox.net
498  206-395-6284               jbiddy@yahoo.com
499  407-557-8857        chauncey_motley@aol.com

                                         web
0               http://www.bentonjohnbjr.com
1           http://www.chanayjeffreyaesq.com
2             http://www.chemeljameslcpa.com
3        http://www.feltzprintingservice.com
4          http://www.printingdimensions.com
..                                       ...
495                http://www.innerlabel.com
496                 http://www.hermarinc.com
497   http://www.simontonhoweschneiderpc.com
498  http://www.warehouseofficepaperprod.com
499  http://www.affiliatedwithtravelodge.com

[500 rows x 12 columns]

In [ ]:
# find duplicate name
filtered_df = df[ df['first_name']=='James' ]
print(filtered_df[filtered_df])

  first_name last_name       company_name             address city   county  \
0      James      Butt  Benton, John B Jr  6649 N Blue Gum St  NaN  Orleans

  state    zip        phone1        phone2            email  \
0    LA  70116  504-621-8927  504-845-1427  jbutt@gmail.com

                            web
0  http://www.bentonjohnbjr.com